name: Deploy stage
on: [push]

jobs:
  Generate_Github_Pages:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: cd ${{ github.workspace }}
      - run: cp ./docs/index.md /tmp
      - run: git checkout HEAD^
      - run: |
          result=0
          diff /tmp/index.md ./docs/index.md || result=$?
          if [[ $result -eq 0 ]]; then
            echo -e 'No new documentation generated! Generate documentation before commiting! See utils/generate_github_pages.sh'
            exit 1
          fi
