name: Code quality template
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string

jobs:
  Pylint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{ github.workspace }}
      - run: pylint ${{ inputs.module_name }}
